# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-09-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitLogAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_clone_url', models.CharField(blank=True, db_index=True, default=b'', max_length=100, verbose_name='gitClone\u8def\u5f84')),
                ('git_path', models.CharField(blank=True, default=b'', max_length=500, verbose_name='\u4ee3\u7801\u8def\u5f84')),
                ('git_author', models.CharField(blank=True, default=b'', max_length=500, verbose_name='\u4ee3\u7801\u63d0\u4ea4\u8005')),
                ('startTime', models.CharField(blank=True, default=b'', max_length=50, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('endTime', models.CharField(blank=True, default=b'', max_length=50, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('commit_freq', models.CharField(blank=True, default=b'', max_length=3, verbose_name='\u7edf\u8ba1\u63d0\u4ea4\u9891\u7387')),
                ('email', models.CharField(blank=True, db_index=True, default=b'', max_length=50, verbose_name='\u63a5\u6536\u6570\u636e\u7684\u90ae\u7bb1')),
                ('status', models.CharField(default=b'active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitLogPubStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.CharField(blank=True, db_index=True, default=b'', max_length=10, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('author', models.CharField(blank=True, db_index=True, default=b'', max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('commit_count', models.IntegerField(default=1, verbose_name='\u63d0\u4ea4\u6b21\u6570')),
                ('commit_path', models.CharField(blank=True, db_index=True, default=b'', max_length=50, verbose_name='\u63d0\u4ea4\u8def\u5f84')),
                ('analyze_id', models.IntegerField(default=1, verbose_name='\u67e5\u8be2id')),
            ],
        ),
    ]
