# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-09-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAnalyse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, default=b'', max_length=200, verbose_name='commitHash')),
                ('auth', models.CharField(blank=True, default=b'', max_length=200, verbose_name='\u63d0\u4ea4\u7528\u6237\u540d')),
                ('auth_email', models.CharField(blank=True, db_index=True, default=b'', max_length=200, verbose_name='\u63d0\u4ea4\u7528\u6237\u5bc6\u7801')),
                ('commit_at', models.DateTimeField(db_index=True)),
                ('add_line', models.IntegerField(default=1, verbose_name='\u7528\u6237\u589e\u52a0\u884c\u6570')),
                ('del_line', models.IntegerField(default=1, verbose_name='\u7528\u6237\u5220\u9664\u884c\u6570')),
                ('company', models.CharField(blank=True, db_index=True, default=b'', max_length=200, verbose_name='\u7528\u6237\u516c\u53f8')),
                ('commit_file', models.CharField(blank=True, default=b'', max_length=200, verbose_name='\u7528\u6237\u63d0\u4ea4\u8def\u5f84')),
                ('commit_path', models.CharField(blank=True, default=b'', max_length=200, verbose_name='\u7528\u6237\u63d0\u4ea4\u5927\u8def\u5f84')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('git_log_url', models.CharField(blank=True, db_index=True, default=b'', max_length=100, verbose_name='\u6587\u4ef6\u8def\u5f84')),
            ],
        ),
        migrations.CreateModel(
            name='GitLogLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_log_url', models.CharField(blank=True, db_index=True, default=b'', max_length=100, verbose_name='gitClone\u8def\u5f84')),
                ('git_log_count', models.IntegerField(default=1, verbose_name='\u62c9\u53d6\u7684\u63d0\u4ea4\u6b21\u6570')),
                ('git_log_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6700\u8fd1\u4e00\u6b21\u62c9\u53d6\u65f6\u95f4')),
            ],
        ),
    ]
